services:
    info_log.user_agent_subscriber:
        class: JuanLuisGarciaBorrego\InfoLogBundle\EventListener\UserAgentSubscriber
        arguments: [@logger]
        tags:
            - { name: kernel.event_subscriber }